### ISSUE TITLE
Mabe lack of some data like dstc4_traindev/data/21/label.json etc,  please check!

### ISSUE THREAD

**Issue by SeekPoint** [TakuyaHiraoka/Dialogue-State-Tracking-using-LSTM#3]
rzai@rzai00:~/prj/Dialogue-State-Tracking-using-LSTM/dstc4_traindev$ python main.py 
/usr/local/lib/python2.7/dist-packages/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Using gpu device 0: GeForce GTX 1080 (CNMeM is disabled, cuDNN 5005)
Start to construct doc2vec from given dialogs.
['dstc4_train', 'dstc4_dev', 'dstc4_test']
<dataset_walker.dataset_walker object at 0x7f2d6796df90>
<dataset_walker.dataset_walker object at 0x7f2d6796dfd0>
<dataset_walker.dataset_walker object at 0x7f2db52f6f50>
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    LSTMWithBOWTracker.constructDoc2vec(nameDataS2V=["dstc4_train","dstc4_dev","dstc4_test"])
  File "/home/rzai/prj/Dialogue-State-Tracking-using-LSTM/dstc4_traindev/scripts/LSTMWithBOW.py", line 658, in constructDoc2vec
    for call in dataset:
  File "/home/rzai/prj/Dialogue-State-Tracking-using-LSTM/dstc4_traindev/scripts/dataset_walker.py", line 42, in **iter**
    raise RuntimeError,'Cant score : cant open labels file %s' % (labels_filename)
RuntimeError: Cant score : cant open labels file /home/rzai/prj/Dialogue-State-Tracking-using-LSTM/dstc4_traindev/data/21/label.json
rzai@rzai00:~/prj/Dialogue-State-Tracking-using-LSTM/dstc4_traindev$

**Comment by TakuyaHiraoka** [comment]
Hi, thank you for your comment. 

DSTS didn't provide complete data. 
The problem was that the program (main.py) was set to use complete data, for some reason. 
So I modified the setting to use partial data only.
