### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by SeekPoint** [TakuyaHiraoka/Dialogue-State-Tracking-using-LSTM#4]
3493/3500(epoch/max epoch)
3494/3500(epoch/max epoch)
3495/3500(epoch/max epoch)
3496/3500(epoch/max epoch)
3497/3500(epoch/max epoch)
3498/3500(epoch/max epoch)
3499/3500(epoch/max epoch)
Doc2Vec was constructed with:
[<dataset_walker.dataset_walker object at 0x7efd47a65b10>, <dataset_walker.dataset_walker object at 0x7efd47a65550>]
, stored to LearnedDoc2Vec.d2v
Create o dictionary required in ensembler
In both of learning and tracking,
the tracker store output of LSTM at each turn in Sub.dial,
and tracker ignore the utterance which is not related to main task.
and tracker consider one subdialog at one sequence.
and the output of LSTM is combined with that of baseline.
and features made by M1s are used in input.
and distributed sentence reprentation is used instead of BOW and m/home/rzai/prj/Dialogue-State-Tracking-using-LSTM/dstc4_traindev/scripts/LSTMWithBOW.py:447: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if avrV==None:
eta info.
FuzzyMatchingResult.pic Dictionary are loaded.
M1Vec.pic.gzwas not found. Dictionary are newly created.
numClassFeature.pic was not found. learn() is required before tracking.
numSentenceFeature.pic was not found. learn() is required before tracking.
numM1Feature.pic was not found. learn() is required before tracking.
Doc2vec was loaded.
Start learning LSTM, and make dictionary file
Star make dictionary: variable name -> corresponding index of element in i/o vector
totalNumSlot:30
outputSize:5608
inputSize:2228
Start learning Network
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    lstm.learn(pathdataset=["dstc4_train"], EPOCHS_PER_CYCLE = 1, CYCLES = 1)#the pathdataset which same with that in latter ensembler should be set.
  File "/home/rzai/prj/Dialogue-State-Tracking-using-LSTM/dstc4_traindev/scripts/LSTMWithBOW.py", line 347, in learn
    if "frame_label" in label:
TypeError: argument of type 'NoneType' is not iterable
Write fuzzymatching result to file.
Write M1 vector comp. result to file.
                                                                                                                                                                                           7041,1        Bot

**Comment by TakuyaHiraoka** [comment]
Sorry for my late reply. 
I will work on the issue this weekend.

**Comment by TakuyaHiraoka** [comment]
HI, 
I had modified the learning part in LSTMWithBOW.py. 
Would you check if the issue is fixed?

**Comment by SeekPoint** [comment]
Got a different error:

WARNING:gensim.models.word2vec:under 10 jobs per worker: consider setting a smaller `batch_words' for smoother alpha decay
3498/3500(epoch/max epoch)
WARNING:gensim.models.word2vec:under 10 jobs per worker: consider setting a smaller`batch_words' for smoother alpha decay
3499/3500(epoch/max epoch)
Doc2Vec was constructed with:
[<dataset_walker.dataset_walker object at 0x7f6e4b2472d0>, <dataset_walker.dataset_walker object at 0x7f6e4b2bdf90>]
, stored to LearnedDoc2Vec.d2v
Create o dictionary required in ensembler
In both of learning and tracking,
the tracker store output of LSTM at each turn in Sub.dial,
and tracker ignore the utterance which is not related to main task.
and tracker consider one subdialog at one sequence.
and the output of LSTM is combined with that of baseline.
and features made by M1s are used in input.
and distributed sentence reprentation is used instead of BOW and meta info.
FuzzyMatchingResult.pic Dictionary are loaded.
M1Vec.pic.gz Dictionary are loaded.
TSizeClasssFeature=1611
numSentenceFeature.pic was not found. learn() is required before tracking. 
TSizeM1Feature=17
Doc2vec was loaded.
Start learning LSTM, and make dictionary file
Star make dictionary: variable name -> corresponding index of element in i/o vector
totalNumSlot:30
outputSize:5608
inputSize:2228
Start learning Network
/home/rzai/prj/Dialogue-State-Tracking-using-LSTM/dstc4_traindev/scripts/LSTMWithBOW.py:447: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if avrV==None:
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    lstm.learn(pathdataset=["dstc4_train"], EPOCHS_PER_CYCLE = 1, CYCLES = 1)#the pathdataset which same with that in latter ensembler should be set.
  File "/home/rzai/prj/Dialogue-State-Tracking-using-LSTM/dstc4_traindev/scripts/LSTMWithBOW.py", line 344, in learn
    convInput=self._translateUtteranceIntoInputVector(uttr,call)
  File "/home/rzai/prj/Dialogue-State-Tracking-using-LSTM/dstc4_traindev/scripts/LSTMWithBOW.py", line 466, in _translateUtteranceIntoInputVector
    convM1Input=self.__calculateM1sInputFeature(self.tagsets,convM1Input, utter)
  File "/home/rzai/prj/Dialogue-State-Tracking-using-LSTM/dstc4_traindev/scripts/LSTMWithBOW.py", line 528, in __calculateM1sInputFeature
    tokensWPOSUtter=nltk.pos_tag(tokensUtter)
  File "/usr/local/lib/python2.7/dist-packages/nltk/tag/__init__.py", line 111, in pos_tag
    return _pos_tag(tokens, tagset, tagger)  
  File "/usr/local/lib/python2.7/dist-packages/nltk/tag/__init__.py", line 82, in _pos_tag
    tagged_tokens = tagger.tag(tokens)
  File "/usr/local/lib/python2.7/dist-packages/nltk/tag/perceptron.py", line 152, in tag
    context = self.START + [self.normalize(w) for w in tokens] + self.END
  File "/usr/local/lib/python2.7/dist-packages/nltk/tag/perceptron.py", line 226, in normalize
    elif word[0].isdigit():
IndexError: string index out of range
Write fuzzymatching result to file.
Write M1 vector comp. result to file.
rzai@rzai00:~/prj/Dialogue-State-Tracking-using-LSTM/dstc4_traindev$
